apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: ns-prod-finkargo
  labels:
    app.kubernetes.io/team: devops
    app.kubernetes.io/company: finkargo
    app.kubernetes.io/stage: produccion
    app.kubernetes.io/group: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: python:3.9.13-buster
        command: [ "sleep", "3600" ]  # 🔹 Esto mantendrá el contenedor en ejecución
        resources:
          limits:
            memory: "150Mi"
            cpu: "0.5"
          requests:
            memory: "100Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: ns-prod-finkargo
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
